oltp_db:
  host: "demo-ecommerce-demo-dataengineering.k.aivencloud.com"
  port: 17613
  database: "ecommerce"
  user: "avnadmin"
  password: "AVNS_1muvxS_KAQKH-PtVKOL"

bigquery:
  project_id: "ngds-data-engineer"
  key_path: "secrets/ngds_bigquery_service_account.json"
  dataset: "ecommerce_dw"
